### ISSUE TITLE
Implement dynamic commands

### ISSUE THREAD

**Issue by mr5z** [butler1233/stackoverflow-chatbot#25]
Preferably through RESTful approach.

Teach:
Bot, learn test https://custom-command?param1={0}&param2={1}

Execute:
Bot, test param1 param2

**Comment by butler1233** [comment]
I thought that's what you were working on? Or did you give up because Firestore is aids?

**Comment by mr5z** [comment]
The previous implementation is the first step, this is an upgrade of that.
